#!/bin/sh

#0
sh lab1_rm

#1
cd ~
mkdir test

#2
cd test
find /etc -type f | while read line; do echo ${line} -f; done > list
find /etc -type d | while read line; do echo ${line} -d; done >> list

#3
find /etc -type d | wc -l >> list
find /etc -type f -name "[.]*" | wc -l >> list

#4
mkdir links

#5
cd links
ln ../list list_hlink

#6
ln -s ../list list_slink

#7
echo "7. list_hlink: $(ls -l list_hlink | awk '{print $2}')"
echo "7. list_slink: $(ls -l list_slink | awk '{print $2}')"
cd ..
echo "7. list: $(ls -l list | awk '{print $2}')"

#8
cd links
cat ../list | wc -l >> list_hlink

#9
cmp -s list_hlink list_slink && echo "9. YES" || echo "9. NO"

#10
cd ..
mv list list1

#11
cd links
cmp -s list_hlink list_slink && echo "11. YES" || echo "11. NO"

#12
cd ~
ln ~/test/list1 list_link

#13
find /etc -type f -name "*\.conf" > list_conf

#14
find /etc -maxdepth 1 -type d -name "*\.d" > list_d

#15
cat list_conf > list_conf_d
cat list_d >> list_conf_d

#16
cd test
mkdir .sub

#17
cp ~/list_conf_d ~/test/.sub

#18
cp --backup=simple ~/list_conf_d ~/test/.sub

#19
echo "19."
find

#20
cd ~
man man > man.txt

#21
split man.txt -b 1K

#22
mkdir man.dir

#23
mv x* man.dir

#24
cd man.dir
cat x* > man.txt

#25
cmp -s man.txt ../man.txt && echo "25. YES" || echo "25. NO"

#26
cd ..
echo -e "some text\nin the beginning\n$(cat man.txt)\nalso some text\nin the end" > man.txt

#27
diff -u man.dir/man.txt man.txt > man_diff

#28
mv man_diff man.dir/man_diff

#29
cd man.dir
patch -s man.txt < man_diff

#30
cmp man.txt ../man.txt && echo "30. YES" || echo "30. NO"
